version: '3'
services:
  web:
    image: python:3.8
    command: bash -c "pip install -r requirements.txt && python app.py"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"