### Hello Endpoint
GET http://localhost:8080/hello/John
content-type: application/json


### Post endpoint
POST http://localhost:8080/post/endpoint
content-type: application/json

{
  "bubble_text": "beep boop beep"
}
